# Generated by Django 6.0 on 2025-12-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_units',
            new_name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='available_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reciperequirements',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
